CREATE TABLE [General].[Shops]
(
	[ShopID]					UNIQUEIDENTIFIER NOT NULL,
	[ShopName]					NVARCHAR(200) NOT NULL,
	[ShopOwnerID]				UNIQUEIDENTIFIER NOT NULL,
	[ShopLocation]				NVARCHAR(MAX) NOT NULL,
	[ShopCreationDate]			DATETIME NOT NULL,

CONSTRAINT [PK_Shops] PRIMARY KEY ([ShopID] ASC)
)
