CREATE TABLE [Security].[UserRole]
(
	[UserRoleID]	UNIQUEIDENTIFIER NOT NULL,
	[UserID]		INT NOT NULL,
	[RoleID]		INT NOT NULL,
	[ModifiedOn]	DATETIME NOT NULL,
CONSTRAINT [PK_UserRole] PRIMARY KEY CLUSTERED ([UserRoleID] ASC)
)
